CREATE DATABASE IF NOT EXISTS FACULDADE;

USE FACULDADE;

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
	    CODIGO_FUNCIONARIO INT AUTO_INCREMENT,
	    NOME_FUNCIONARIO VARCHAR(255) NOT NULL,
	    DATA_ADMISSAO DATE NOT NULL,
	    DATA_DEMISSAO DATE,
	    PRIMARY KEY (CODIGO_FUNCIONARIO)
	 );

CREATE TABLE IF NOT EXISTS TITULACAO (
	    CODIGO_TITULACAO INT AUTO_INCREMENT,
	    NOME_TITULACAO VARCHAR(25) NOT NULL,
	    DESCRICAO_TITULACAO VARCHAR(255),
	    PRIMARY KEY (CODIGO_TITULACAO)
	 );

CREATE TABLE IF NOT EXISTS PROFESSOR (
	    CODIGO_FUNCIONARIO INT,
	    MATRICULA_PROFESSOR INT NOT NULL,
	    CODIGO_TITULACAO INT,
	    PRIMARY KEY (CODIGO_FUNCIONARIO, MATRICULA_PROFESSOR),
	    FOREIGN KEY (CODIGO_TITULACAO)
	    REFERENCES TITULACAO(CODIGO_TITULACAO)
	);
